// =========================================
// AUTHOR: Radek Mikulka
// DATE:   24.10.2024
// =========================================

namespace Pharaoh
{
	public enum EScreenId
	{
		None = 0,
		PauseCoreGame = 1,
		CoreGameOverlay = 2,
		Dialog = 3,
		DialogOverlay = 4,
		DialogueWindow = 5,
		Shop = 6,
		Contracts = 7,
		Dispatch = 8,
		Depot = 9,
		RateUs = 10,
		NativeRateUsEditor = 11,
		DecadePass = 12,
		DecadePassPremium = 13,
		Info = 14,
		Settings = 15,
		Headquarters = 16,
		SaveProgress = 17,
		Customize = 18,
		Warehouse = 19,
		RateUsFeedback = 20,
		NewYear = 21,
		PopUpOfferMenu = 22,
		VehicleDetail = 23,
		City = 24,
		ContractRewards = 25,
		Factories = 26,
		SpecialBuildings = 27,
		Parcel = 28,
		Factory = 29,
		NewMaterialUnlocked = 30,
		GetMoreMaterial = 31,
		FactoryManagement = 32,
		DepotUpgrade = 33,
		DispatchCenter = 34,
		ProfileConflict = 35,
		FuelStation = 36,
		FuelStationManage = 37,
		CityUpgrade = 38,
		WarehouseUpgrade = 39,
		FullscreenVehicleDetail = 40,
		VehicleFollow = 41,
		TermsOfUse = 42,
		BadGameVersion = 43,
		NewLocationUnlocked = 44,
		SaveProgressPopUp = 45,
		FacebookLikePopUp = 46,
		FacebookConnectPopUp = 47,
		InfoScreenAlternate = 48,
		DispatcherHired = 49,
		EventOverview = 50,
		EventPassPremium = 51,
		LeaderboardRewards = 52,
		LeaderboardFinished = 53,
		CompanyProfile = 54,
		RawMaterials = 55,
		CompanyGrowth = 56,
		LanguageSelect = 57,
	}
}