namespace TycoonBuilder
{
    public enum EUiRect
    {
        None = 0,
        VehicleInDispatchMenu = 1,
        DispatchCentralMenuButton = 2,
        DispatchInDispatchCentralMenu = 3,
        WarehouseMenuButton = 4,
        VehicleDepotButton = 5,
        TutorialDepotVehicle = 6,
        BuyVehicleButton = 7,
        ContractInfoRect = 8,
        FactoriesMenuButton = 9,
        FoundryFactoryButton = 10,
        CraftInFactoryButton = 11,
        GetMoreMaterialButton = 12,
        GoInNeedResourcesScreen = 13,
        CityMenuPassengers = 14,
        CityMenuManageButton = 15,
        CityMenuContractsTabButton = 16,
        FirstPassengerContract = 17,
        ContractsMenuButton = 18,
        RoadSlopeContractButton = 19,
        CityMenuManageHighlightRect = 20,
        CityMenuPassengersHighlightRect = 21,
        CityPlotBuyButton = 22,
        FirstSpecialBuildingRect = 23,
        BrokenVehicleRect = 24,
        VehicleDurabilityInfo = 25,
        VehicleRepairButton = 26,
        VehicleToUpgradeRect = 27,
        CurrenciesRect = 28,
        VehicleUpgradeBlock = 29,
        ContractWarehouseIcon = 30,
        BuySpecialBuildingButton = 31,
        DurabilityContractInfoRect = 32,
        FirstEventContract = 33,
        FirstStoryContract = 34,
    }
}