namespace ServerData
{
    public enum EModificationSource
    {
        None = 0,
        OfferReward = 1,
        ClaimDispatch = 2,
        DecadePassFree = 3,
        DeleteResource = 4,
        VehicleUpgrade = 5,
        BuyVehicle = 6,
        VehicleSpeedupContract = 7,
        WarehouseUpgrade = 8,
        WarehouseUpgradeSpeedup = 9,
        CityUpgrade = 10,
        CityUpgradeSpeedup = 11,
        CraftInFactory = 12,
        FactoryCollect = 13,
        BuyFactorySlot = 14,
        UpgradeFactory = 15,
        StoryContractDispatch = 16,
        ClaimContract = 17,
        BuyBuildingPlot = 18,
        BuySpecialBuilding = 19,
        FuelStationUpgrade = 20,
        UseConsumable = 21,
        GetMoreMaterial = 23,
        ClaimPassengerContract = 24,
        RepairVehicle = 25,
        VehicleDepoUpgrade = 26,
        VehicleDepoUpgradeSpeedup = 27,
        FactoryUpgradeSpeedup = 28,
        FuelStationSpeedup = 29,
        AdminEdit = 30,
        IndustryDispatch = 31,
        OfferPrice = 32,
        RepairFactory = 33,
        PassengerDispatch = 34,
        Cheat = 35,
        VehicleSpeedupPassenger = 36,
        VehicleSpeedupResource = 37,
        EventPassFree = 38,
        EventLeaderboard = 39,
        DecadePassFreeDoubled = 40,
        DecadePassPremium = 41,
        EventPassFreeDoubled = 42,
        EventPassPremium = 43,
        DailyTasks = 44,
        WeeklyTasks = 45,
        FinalDailyReward = 46,
        EventBonusBank = 47,
        EventContractDispatch = 48,
        ClaimEventContract = 49,
        GetMoreCollect = 50,
        Project = 51,
        SocialMediaReward = 52,
        PromoCode = 53,
        ExcavationSiteReward = 54,
        SpecialDeliveryReward = 55, // reserved for future
    }
}